// Code generated by scripts/gen-curl-options.sh; DO NOT EDIT.
//
// Arity is established empirically rather than by scraping help text, whose
// argument markup is inconsistent across curl versions. Every option curl
// advertises is invoked bare, and curl's own answer decides the entry:
//
//	curl: option --proxy: requires parameter
//
// The table only shapes the *metadata* pogo records. Execution always replays
// the user's original argv, so a stale or wrong entry here degrades a history
// record; it can never change what curl actually does.
//
// Generated from curl 8.6.0, plus options added by later releases.

package curlargs

// Long options that consume the following argument.
var longWithValue = map[string]struct{}{
	"abstract-unix-socket": {}, "alt-svc": {}, "aws-sigv4": {}, "cacert": {}, "capath": {},
	"cert": {}, "cert-type": {}, "ciphers": {}, "config": {}, "connect-timeout": {}, "connect-to": {},
	"continue-at": {}, "cookie": {}, "cookie-jar": {}, "create-file-mode": {}, "crlfile": {},
	"curves": {}, "data": {}, "data-ascii": {}, "data-binary": {}, "data-raw": {}, "data-urlencode": {},
	"delegation": {}, "dns-interface": {}, "dns-ipv4-addr": {}, "dns-ipv6-addr": {}, "dns-servers": {},
	"doh-url": {}, "dump-header": {}, "ech": {}, "egd-file": {}, "engine": {}, "etag-compare": {},
	"etag-save": {}, "expect100-timeout": {}, "form": {}, "form-string": {}, "ftp-account": {},
	"ftp-alternative-to-user": {}, "ftp-method": {}, "ftp-port": {}, "ftp-ssl-ccc-mode": {},
	"happy-eyeballs-timeout-ms": {}, "haproxy-clientip": {}, "header": {}, "hostpubmd5": {},
	"hostpubsha256": {}, "hsts": {}, "interface": {}, "ip-tos": {}, "ipfs-gateway": {}, "json": {},
	"keepalive-cnt": {}, "keepalive-time": {}, "key": {}, "key-type": {}, "krb": {}, "libcurl": {},
	"limit-rate": {}, "local-port": {}, "login-options": {}, "mail-auth": {}, "mail-from": {},
	"mail-rcpt": {}, "max-filesize": {}, "max-redirs": {}, "max-time": {}, "netrc-file": {},
	"noproxy": {}, "oauth2-bearer": {}, "output": {}, "output-dir": {}, "parallel-max": {},
	"pass": {}, "pinnedpubkey": {}, "preproxy": {}, "proto": {}, "proto-default": {}, "proto-redir": {},
	"proxy": {}, "proxy-cacert": {}, "proxy-capath": {}, "proxy-cert": {}, "proxy-cert-type": {},
	"proxy-ciphers": {}, "proxy-crlfile": {}, "proxy-header": {}, "proxy-key": {}, "proxy-key-type": {},
	"proxy-pass": {}, "proxy-pinnedpubkey": {}, "proxy-service-name": {}, "proxy-tls13-ciphers": {},
	"proxy-tlsauthtype": {}, "proxy-tlspassword": {}, "proxy-tlsuser": {}, "proxy-user": {},
	"proxy1.0": {}, "pubkey": {}, "quote": {}, "random-file": {}, "range": {}, "rate": {},
	"referer": {}, "request": {}, "request-target": {}, "resolve": {}, "retry": {}, "retry-delay": {},
	"retry-max-time": {}, "sasl-authzid": {}, "service-name": {}, "sigalgs": {}, "socks4": {},
	"socks4a": {}, "socks5": {}, "socks5-gssapi-service": {}, "socks5-hostname": {}, "speed-limit": {},
	"speed-time": {}, "ssl-sessions": {}, "stderr": {}, "telnet-option": {}, "tftp-blksize": {},
	"time-cond": {}, "tls-max": {}, "tls13-ciphers": {}, "tlsauthtype": {}, "tlspassword": {},
	"tlsuser": {}, "trace": {}, "trace-ascii": {}, "trace-config": {}, "unix-socket": {}, "upload-file": {},
	"upload-flags": {}, "url": {}, "url-query": {}, "user": {}, "user-agent": {}, "variable": {},
	"vlan-priority": {}, "write-out": {},
}

// Long options that stand alone.
var longBoolean = map[string]struct{}{
	"anyauth": {}, "append": {}, "basic": {}, "ca-native": {}, "cert-status": {}, "compressed": {},
	"compressed-ssh": {}, "create-dirs": {}, "crlf": {}, "digest": {}, "disable": {}, "disable-eprt": {},
	"disable-epsv": {}, "disallow-username-in-url": {}, "doh-cert-status": {}, "doh-insecure": {},
	"dump-ca-embed": {}, "fail": {}, "fail-early": {}, "fail-with-body": {}, "false-start": {},
	"form-escape": {}, "ftp-create-dirs": {}, "ftp-pasv": {}, "ftp-pret": {}, "ftp-skip-pasv-ip": {},
	"ftp-ssl-ccc": {}, "ftp-ssl-control": {}, "get": {}, "globoff": {}, "haproxy-protocol": {},
	"head": {}, "help": {}, "http0.9": {}, "http1.0": {}, "http1.1": {}, "http2": {}, "http2-prior-knowledge": {},
	"http3": {}, "http3-only": {}, "ignore-content-length": {}, "include": {}, "insecure": {},
	"ipv4": {}, "ipv6": {}, "junk-session-cookies": {}, "list-only": {}, "location": {}, "location-trusted": {},
	"mail-rcpt-allowfails": {}, "manual": {}, "metalink": {}, "mptcp": {}, "negotiate": {},
	"netrc": {}, "netrc-optional": {}, "next": {}, "no-alpn": {}, "no-buffer": {}, "no-clobber": {},
	"no-keepalive": {}, "no-npn": {}, "no-progress-meter": {}, "no-sessionid": {}, "noproxy-env": {},
	"ntlm": {}, "ntlm-wb": {}, "out-null": {}, "parallel": {}, "parallel-immediate": {}, "path-as-is": {},
	"post301": {}, "post302": {}, "post303": {}, "progress-bar": {}, "proxy-anyauth": {}, "proxy-basic": {},
	"proxy-ca-native": {}, "proxy-digest": {}, "proxy-http2": {}, "proxy-insecure": {}, "proxy-negotiate": {},
	"proxy-ntlm": {}, "proxy-ssl-allow-beast": {}, "proxy-ssl-auto-client-cert": {}, "proxy-tlsv1": {},
	"proxytunnel": {}, "raw": {}, "remote-header-name": {}, "remote-name": {}, "remote-name-all": {},
	"remote-time": {}, "remove-on-error": {}, "retry-all-errors": {}, "retry-connrefused": {},
	"sasl-ir": {}, "show-error": {}, "silent": {}, "skip-existing": {}, "socks5-basic": {},
	"socks5-gssapi": {}, "socks5-gssapi-nec": {}, "ssl": {}, "ssl-allow-beast": {}, "ssl-auto-client-cert": {},
	"ssl-no-revoke": {}, "ssl-reqd": {}, "ssl-revoke-best-effort": {}, "sslv2": {}, "sslv3": {},
	"styled-output": {}, "suppress-connect-headers": {}, "tcp-fastopen": {}, "tcp-nodelay": {},
	"tftp-no-options": {}, "tls-earlydata": {}, "tlsv1": {}, "tlsv1.0": {}, "tlsv1.1": {},
	"tlsv1.2": {}, "tlsv1.3": {}, "tr-encoding": {}, "trace-ids": {}, "trace-time": {}, "use-ascii": {},
	"verbose": {}, "version": {}, "xattr": {},
}

// Short options that consume a value: either the remainder of the cluster
// (-dfoo) or the next argument (-d foo).
var shortWithValue = map[byte]struct{}{
	'A': {}, 'C': {}, 'D': {}, 'E': {}, 'F': {}, 'H': {}, 'K': {}, 'P': {}, 'Q': {}, 'T': {},
	'U': {}, 'X': {}, 'Y': {}, 'b': {}, 'c': {}, 'd': {}, 'e': {}, 'm': {}, 'o': {}, 'r': {},
	't': {}, 'u': {}, 'w': {}, 'x': {}, 'y': {}, 'z': {},
}

// Short options that stand alone and may be clustered (-sSL).
var shortBoolean = map[byte]struct{}{
	'#': {}, '0': {}, '1': {}, '2': {}, '3': {}, '4': {}, '6': {}, ':': {}, 'B': {}, 'G': {},
	'I': {}, 'J': {}, 'L': {}, 'M': {}, 'N': {}, 'O': {}, 'R': {}, 'S': {}, 'V': {}, 'Z': {},
	'a': {}, 'f': {}, 'g': {}, 'h': {}, 'i': {}, 'j': {}, 'k': {}, 'l': {}, 'n': {}, 'p': {},
	'q': {}, 's': {}, 'v': {},
}
